[
    {
        "name": "Ian Devling",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/cto.jpg",
        "positionName": "Chief Executive Officer ",
        "id": "O-6066",
        "parentId": "",
    },
    {
        "name": "Davolio Nancy",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "CTO ",
        "id": "O-6067",
        "parentId": "O-6066",
    },
    {
        "name": " Leverling Janet",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/female.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "CTO ",
        "id": "O-6068",
        "parentId": "O-6066",
    },
    {
        "name": " Leverling Janet",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/female.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "CTO ",
        "id": "O-6069",
        "parentId": "O-6066",
    },
    {
        "name": " Leverling Janet",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/female.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "CTO ",
        "id": "O-6070",
        "parentId": "O-6066",
    },
    {
        "name": " Leverling Janet",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/female.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "CTO ",
        "id": "O-6071",
        "parentId": "O-6067",
    },
    {
        "name": "Fuller Andrew",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Linear Manager",
        "id": "O-6072",
        "parentId": "O-6067",
    },
    {
        "name": "Peacock Margaret",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "CEO",
        "id": "O-6073",
        "parentId": "O-6067",
    },
    {
        "name": "Buchanan Steven",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Head of direction",
        "id": "O-6074",
        "parentId": "O-6067",
    },
    {
        "name": "Suyama Michael",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior sales manager",
        "id": "O-6075",
        "parentId": "O-6067",
    },
    {
        "name": "King Robert",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior Sales Manager",
        "id": "O-6076",
        "parentId": "O-6067",
    },
    {
        "name": "West Adam",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "CTO",
        "id": "O-6077",
        "parentId": "O-6067",
    },
    {
        "name": "Charlotte Cooper",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior Trader",
        "id": "O-6078",
        "parentId": "O-6067",
    },
    {
        "name": "Yoshi Nagase",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Head of laboratory",
        "id": "O-6079",
        "parentId": "O-6067",
    },
    {
        "name": "Peter Wilson",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Head of channels",
        "id": "O-6080",
        "parentId": "O-6068",
    },
    {
        "name": "Carlos Diaz",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior Android Developer",
        "id": "O-6081",
        "parentId": "O-6068",
    },
    {
        "name": "Sven Petersen",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior Developer",
        "id": "O-6082",
        "parentId": "O-6068",
    },
    {
        "name": "Peter Wilson",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Head of channels",
        "id": "O-6083",
        "parentId": "O-6069",
    },
    {
        "name": "Carlos Diaz",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior Android Developer",
        "id": "O-6084",
        "parentId": "O-6069",
    },
    {
        "name": "Sven Petersen",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior Developer",
        "id": "O-6085",
        "parentId": "O-6069",
    },
    {
        "name": "Peter Wilson",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Head of channels",
        "id": "O-6086",
        "parentId": "O-6070",
    },
    {
        "name": "Carlos Diaz",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior Android Developer",
        "id": "O-6087",
        "parentId": "O-6070",
    },
    {
        "name": "Sven Petersen",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior Developer",
        "id": "O-6088",
        "parentId": "O-6070",
    },
    {
        "name": " Leverling Janet",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/female.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "CTO ",
        "id": "O-6089",
        "parentId": "O-6071",
    },
    {
        "name": "Fuller Andrew",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Linear Manager",
        "id": "O-6090",
        "parentId": "O-6071",
    },
    {
        "name": "Peacock Margaret",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "CEO",
        "id": "O-6091",
        "parentId": "O-6071",
    },
    {
        "name": "Buchanan Steven",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Head of direction",
        "id": "O-6092",
        "parentId": "O-6071",
    },
    {
        "name": "Suyama Michael",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior sales manager",
        "id": "O-6093",
        "parentId": "O-6071",
    },
    {
        "name": "King Robert",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior Sales Manager",
        "id": "O-6094",
        "parentId": "O-6071",
    },
    {
        "name": "West Adam",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "CTO",
        "id": "O-6095",
        "parentId": "O-6071",
    },
    {
        "name": "Charlotte Cooper",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg",
        "profileUrl": "http://example.com/employee/profile",
        "positionName": "Senior Trader",
        "id": "O-6096",
        "parentId": "O-6071",
    }
]